spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_eventos_treino
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
